test:
  name: "Request Bond Simulation"
  description: "Benchmark"
  workers:
    type: local
    number: 2
  rounds:
    - label: writepayments
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      callback: benchmarks/callbacks/ppa/request/request.js
      arguments:
        minterOrg: investor
        invokerMspId: investorMSP
        client: investor-client-1
        endorser1Org: spv
        endorser2Org: farmer
        # endorser3Org: spv
        depositReference: deposito123211
        depositBank: Banco123
observer:
  type: local
  interval: 1
monitor:
  interval: 1
  type: ["docker"]
  docker:
    containers: ["all"]
