test:
  name: "Payment Simulation"
  description: "This benchmark scenario will use ppa transactions, to generate a database to analize bond value."
  workers:
    type: local
    number: 2
  rounds:
    - label: transfer
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      callback: benchmarks/callbacks/ppa/transfer/transfer.js
      arguments:
        minterOrg: spv
        invokerMspId: spvMSP
        client: spv-client
        endorser1Org: servicer
        endorser2Org: investor
        # endorser2Org: investor
observer:
  type: local
  interval: 1
monitor:
  interval: 1
  type: ["docker"]
  docker:
    containers: ["all"]
