test:
  name: "Payment Simulation"
  description: "This benchmark scenario will issue bond as a UTXO model."
  workers:
    type: local
    number: 2
  rounds:
    - label: sellingbond
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      callback: benchmarks/callbacks/ppa/sellbonds/sellbonds.js
      arguments:
        minterOrg: spv
        invokerMspId: spvMSP
        client: spv-client
        endorser1Org: servicer
        # endorser2Org: farmer
        endorser2Org: investor
observer:
  type: local
  interval: 1
monitor:
  interval: 1
  type: ["docker"]
  docker:
    containers: ["all"]
